version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5433
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      # - LC_ALL=C.UTF-8
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: 'localhost'
      POSTGRES_PORT: 5432