# Generated by Django 4.1.5 on 2023-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
    ]
