# Generated by Django 4.1.5 on 2023-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_quotes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={},
        ),
    ]
